# Generated by Django 3.0.6 on 2020-05-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventary', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingCartModel',
        ),
    ]
